### ISSUE TITLE
tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by styfle** [sindresorhus/term-size#13]
I'm seeing this error when `process.env.TERM` is undefined and `process.stdout.isTTY` is undefined.

> tput: No value for $TERM and no -T specified

It happens on line 60 when `tput cols` is executed.

https://github.com/sindresorhus/term-size/blob/92aa07ee3a1cc28360af1c908f8a2ae10b6552bd/index.js#L60

**Comment by sindresorhus** [comment]
How are you seeing the error? Errors are silenced by the try/catch. Or do you mean you see it in the terminal as just printed output?

**Comment by styfle** [comment]
Its printed to stderr even though there is a try/catch.

You can reproduce if you deploy to ZEIT Now.

I added some `console.log()` prior to each line to determine exactly when it happens.

![image](https://user-images.githubusercontent.com/229881/70824832-0e9fec00-1db1-11ea-9ad9-388ef806c678.png)

"there was an error" is the message I put in the `catch`

**Comment by styfle** [comment]
Here's the minimal steps to reproduce:

```
npm i -g now
git clone https://github.com/styfle/bug-term-size-tput
cd bug-term-size-tput
now
```

It will look like this: https://zeit.co/testing-internal/bug-term-size-tput/5howzk8xs
