### ISSUE TITLE
.DS_Store files in the package

### ISSUE THREAD

**Issue by reviewher** [sindresorhus/term-size#17]
2.2.0 has a bunch of `.DS_Store` files in the `vendor` subdirectory.  https://unpkg.com/browse/term-size@2.2.0/vendor/

Publishing from a newer npm version should not include them, but in case they are included you can add a `.npmignore` file in the `vendor` subdirectory and add `.DS_Store`

**Comment by sindresorhus** [comment]
I tried publishing a new version with the latest npm version (v6.14.8) and it's still included in the package.

https://github.com/sindresorhus/term-size/releases/tag/v2.2.1

However, interestingly, I cannot see them when installing the package locally.

Regardless, this is an npm bug and should be reported at https://github.com/npm/cli

**Comment by reviewher** [comment]
Can you try putting a `.npmignore` file in the vendor directory:

```
.npmignore
.DS_Store
```
