### ISSUE TITLE
term-size package contains exe file

### ISSUE THREAD

**Issue by myyosi** [sindresorhus/term-size#21]
Hi,
is it possible to eliminate the exe file inside the package?
https://registry.npmjs.org/term-size/-/term-size-2.1.1.tgz
because of this our organization it security web filtering block access to this module and it causes us a lot of trouble.

**Comment by sindresorhus** [comment]
This is not possible. These binaries are unfortunately required.

There are two possible solutions:
1. Node.js supports getting the terminal size reliably natively.
2. https://github.com/nodejs/tooling/issues/76 is implemented, which we could use instead of the binaries.
